version: 2.1
description: |
    An orb to run SAST against Terraform infrastructure code. This orb has been deprecated. Please use the [new orb](https://circleci.com/developer/orbs/orb/ovotech/sast).
display:
    home_url: https://github.com/ovotech/team-cppe/blob/main/circleci-orbs/sast/README.md
    source_url: https://www.github.com/ovotech/team-cppe
commands:
    checkov_static_code_analysis:
        description: |
            Run Checkov Infrastructure as code static analysis against a directory
        parameters:
            baseline:
                default: ""
                description: Path to a .checkov.baseline file to compare. Report will include only failed checks that are not in the baseline
                type: string
            config_file:
                default: ""
                description: checkov configuration file
                type: string
            directory:
                default: .
                description: directory with infrastructure code to scan
                type: string
        steps:
            - checkout
            - run:
                command: pip3 install checkov
                name: Install Checkov command line
            - run:
                command: |
                    #!/bin/bash

                    run_checkov() {
                        checkov --version

                        set --
                        set -- "$@" "--output" "cli"
                        set -- "$@" "--framework" "terraform"
                        set -- "$@" "--download-external-modules" "false"

                        if [ -z "$PARAM_BASELINE" ]; then
                            DEFAULT_BASELINE=$(find "$PARAM_DIRECTORY" -name ".checkov.baseline")
                            if [ -n "$DEFAULT_BASELINE" ]; then
                                set -- "$@" "--baseline" "$DEFAULT_BASELINE"
                            else
                                DEFAULT_BASELINE=$(find . -name ".checkov.baseline")
                                if [ -n "$DEFAULT_BASELINE" ]; then
                                    set -- "$@" "--baseline" "$DEFAULT_BASELINE"
                                fi
                            fi
                        else
                            set -- "$@" "--baseline" "$PARAM_BASELINE"
                        fi

                        if [[ -n "$PARAM_CONFIG_FILE" ]]; then
                            set -- "$@" "--config-file" "$PARAM_CONFIG_FILE"
                        fi

                        echo "running checkov on directory $PARAM_DIRECTORY:"
                        echo "checkov -d $PARAM_DIRECTORY --quiet" "$@"
                        if [ ! -d "./reports_sast_terraform" ]; then
                            mkdir -p ./reports_sast_terraform
                        fi

                        export LOG_LEVEL="WARNING"
                        checkov -d "$PARAM_DIRECTORY" --quiet --output json --soft-fail "$@" 1> ./reports_sast_terraform/${RANDOM}.json
                        checkov -d "$PARAM_DIRECTORY" --quiet "$@"
                    }

                    # Will not run if sourced for bats-core tests.
                    ORB_TEST_ENV="bats-core"
                    if [ "${0#*"$ORB_TEST_ENV"}" == "$0" ]; then
                        run_checkov
                    fi
                environment:
                    PARAM_BASELINE: <<parameters.baseline>>
                    PARAM_CONFIG_FILE: <<parameters.config_file>>
                    PARAM_DIRECTORY: <<parameters.directory>>
                name: Run Checkov command line
            - store_artifacts:
                path: ./reports_sast_terraform/
executors:
    default:
        description: |
            This is a sample executor using Docker and Python.
        docker:
            - image: cimg/python:3.9
jobs:
    checkov_static_code_analysis:
        description: |
            Run Checkov Infrastructure as code static analysis against a directory
        executor: default
        parameters:
            baseline:
                default: ""
                description: Path to a .checkov.baseline file to compare. Report will include only failed checks that are not in the baseline
                type: string
            config_file:
                default: ""
                description: checkov configuration file
                type: string
            directory:
                default: .
                description: directory with infrastructure code to scan
                type: string
        steps:
            - checkov_static_code_analysis:
                baseline: << parameters.baseline >>
                config_file: << parameters.config_file >>
                directory: << parameters.directory >>
examples:
    example:
        description: |
            Sample usage of Terraform SAST orb.
        usage:
            version: "2.1"
            orbs:
                sast-terraform: ovotech/sast-terraform@0.1.0
            workflows:
                example-workflow:
                    jobs:
                        - sast-terraform/checkov_static_code_analysis:
                            directory: terraform/examples

